[project]
name = "filecrawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "henrymdirks", email = "hmd66@case.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "google-api-python-client>=2.200.0",
    "google-auth>=2.58.0",
    "google-auth-oauthlib>=1.4.1",
    "itsdangerous>=2.2.0",
]

[project.scripts]
filecrawler = "filecrawler:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "uvicorn>=0.54.0",
]
